-- AlterTable
ALTER TABLE "User" ADD COLUMN     "usernameChanged" BOOLEAN NOT NULL DEFAULT false,
ALTER COLUMN "lat" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "long" SET DATA TYPE DOUBLE PRECISION;
